#!/bin/bash

HOST=$1
CMD=$2
PORT=$3
ENV=env.default.sh

if [ -e env.$HOST.sh ]; then
    ENV="$ENV env.$HOST.sh"
fi

if [ -e $CMD.$HOST.sh ] ; then 
    SHSC=$CMD.$HOST.sh ;
else 
    SHSC=$CMD.default.sh ;
fi

ENVSTR="HOST=$HOST"

if [ $PORT ]; then
    ENVSTR=$ENVSTR"; export SWFTPORT=$PORT"
fi

if [ ! -d logs ]; then mkdir logs; fi
if [ ! -e $SHSC ]; then
    echo $HOST  $CMD    EMPTY
    exit 0
fi

if ( (cat $ENV; echo $ENVSTR; cat $SHSC) | ssh -T $HOST ) > \
    logs/$HOST.$CMD.out 2> logs/$HOST.$CMD.err; then
    echo $HOST  $CMD    OK
    exit 0
else
    echo $HOST  $CMD    FAIL
    cat $SHSC
    cat logs/$HOST.$CMD.out logs/$HOST.$CMD.err
    exit 1
fi
